apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: upgrade-policy-cluster
  region: us-west-2
  version: "1.34"
  # UpgradePolicy allows you to specify the support type for your cluster
  # Valid values are "STANDARD" and "EXTENDED (default)"
  # - https://docs.aws.amazon.com/eks/latest/APIReference/API_UpgradePolicyRequest.html
  upgradePolicy:
    supportType: "EXTENDED"

# Managed node group
managedNodeGroups:
  - name: mng-1
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
